# Generated by Django 4.1.2 on 2023-02-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
