# Generated by Django 4.1.4 on 2023-02-28 15:43

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social_platform', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_editorjs.fields.EditorJsField(default=''),
            preserve_default=False,
        ),
    ]
