# Generated by Django 4.1.4 on 2024-01-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_platform', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
