# Generated by Django 4.1.4 on 2024-01-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_platform', '0013_remove_post_content_post_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='content',
        ),
    ]
