# Generated by Django 4.1.2 on 2022-12-29 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.CharField(default='67891f01ab3b9632adf3494a623fa79d5affb364764c028da36f9ac62379d891cf8805e2d8b9121ac1373b397d9db5efd963cb5c072c00e4b427f3617e125f1fd4a97692b5554649eac59d1eb872b5f226e86e87a7f1cf9dee8c4797072c0da275f22ae0ac19771d225693ca6319ebedd7025f9be44eaa38b35b8c3ec7f54b3b41d37a462b6dbfb987b3888136f31a69df776ac51d409925d41004e1c4c4583ff6ab144cd098b1fd0d6eaae5e7e15f0e68c15bcb1672322667.668143', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='nothing to see here', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='image_file',
            field=models.ImageField(default='default.ico', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.CharField(default='Basic', max_length=20),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('content_img', models.CharField(max_length=20, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
