# Generated by Django 4.1.2 on 2023-02-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
