# Generated by Django 4.1.2 on 2023-02-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_follower_count_user_following_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
    ]
