# Generated by Django 4.1.4 on 2023-04-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_invalidtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidtoken',
            name='token',
            field=models.CharField(max_length=1000),
        ),
    ]
