# Generated by Django 4.1.4 on 2023-04-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_invalidtoken_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvalidToken',
            new_name='InvalidAccessToken',
        ),
    ]
